namespace InkkSlinger.UI.Telemetry;

/// <summary>
/// ScrollViewer aggregate telemetry snapshot.
/// </summary>
internal readonly record struct ScrollViewerTelemetrySnapshot(
    int WheelEvents,
    int WheelHandled,
    int SetOffsetCalls,
    int SetOffsetNoOpCalls,
    float TotalHorizontalDelta,
    float TotalVerticalDelta,
    int ScrollToHorizontalOffsetCallCount,
    int ScrollToVerticalOffsetCallCount,
    int InvalidateScrollInfoCallCount,
    int HandleMouseWheelCallCount,
    double HandleMouseWheelMilliseconds,
    int HandleMouseWheelHandledCount,
    int HandleMouseWheelIgnoredDisabledCount,
    int HandleMouseWheelIgnoredZeroDeltaCount,
    double SetOffsetsMilliseconds,
    int SetOffsetsExternalSourceCount,
    int SetOffsetsHorizontalScrollBarSourceCount,
    int SetOffsetsVerticalScrollBarSourceCount,
    int SetOffsetsWorkCount,
    int SetOffsetsDeferredLayoutPathCount,
    int SetOffsetsVirtualizingMeasureInvalidationPathCount,
    int SetOffsetsVirtualizingArrangeOnlyPathCount,
    int SetOffsetsTransformInvalidationPathCount,
    int SetOffsetsManualArrangePathCount,
    int PopupCloseCallCount,
    int ArrangeContentForCurrentOffsetsCallCount,
    double ArrangeContentForCurrentOffsetsMilliseconds,
    int ArrangeContentSkippedNoContentCount,
    int ArrangeContentSkippedZeroViewportCount,
    int ArrangeContentTransformPathCount,
    int ArrangeContentOffsetPathCount,
    int UpdateScrollBarValuesCallCount,
    double UpdateScrollBarValuesMilliseconds,
    int UpdateHorizontalScrollBarValueCallCount,
    double UpdateHorizontalScrollBarValueMilliseconds,
    int UpdateVerticalScrollBarValueCallCount,
    double UpdateVerticalScrollBarValueMilliseconds,
    int HorizontalValueChangedCallCount,
    double HorizontalValueChangedMilliseconds,
    double HorizontalValueChangedSetOffsetsMilliseconds,
    int HorizontalValueChangedSuppressedCount,
    int VerticalValueChangedCallCount,
    double VerticalValueChangedMilliseconds,
    double VerticalValueChangedSetOffsetsMilliseconds,
    int VerticalValueChangedSuppressedCount,
    int MeasureOverrideCallCount,
    double MeasureOverrideMilliseconds,
    int ArrangeOverrideCallCount,
    double ArrangeOverrideMilliseconds,
    int ResolveBarsAndMeasureContentCallCount,
    double ResolveBarsAndMeasureContentMilliseconds,
    int ResolveBarsAndMeasureContentIterationCount,
    int ResolveBarsAndMeasureContentHorizontalFlipCount,
    int ResolveBarsAndMeasureContentVerticalFlipCount,
    int ResolveBarsAndMeasureContentSingleMeasurePathCount,
    int ResolveBarsAndMeasureContentRemeasurePathCount,
    int ResolveBarsAndMeasureContentFallbackCount,
    int ResolveBarsAndMeasureContentInitialHorizontalVisibleCount,
    int ResolveBarsAndMeasureContentInitialHorizontalHiddenCount,
    int ResolveBarsAndMeasureContentInitialVerticalVisibleCount,
    int ResolveBarsAndMeasureContentInitialVerticalHiddenCount,
    int ResolveBarsAndMeasureContentResolvedHorizontalVisibleCount,
    int ResolveBarsAndMeasureContentResolvedHorizontalHiddenCount,
    int ResolveBarsAndMeasureContentResolvedVerticalVisibleCount,
    int ResolveBarsAndMeasureContentResolvedVerticalHiddenCount,
    int ResolveBarsForArrangeCallCount,
    double ResolveBarsForArrangeMilliseconds,
    int ResolveBarsForArrangeIterationCount,
    int ResolveBarsForArrangeHorizontalFlipCount,
    int ResolveBarsForArrangeVerticalFlipCount,
    int MeasureContentCallCount,
    double MeasureContentMilliseconds,
    int UpdateScrollBarsCallCount,
    double UpdateScrollBarsMilliseconds)
{
    public int SetOffsetsCallCount => SetOffsetCalls;

    public int SetOffsetsNoOpCount => SetOffsetNoOpCalls;
}

/// <summary>
/// ScrollViewer runtime diagnostics snapshot.
/// </summary>
internal readonly record struct ScrollViewerRuntimeDiagnosticsSnapshot(
    bool ShowHorizontalBar,
    bool ShowVerticalBar,
    bool HasPreviousScrollBarResolution,
    bool PreviousShowHorizontalScrollBar,
    bool PreviousShowVerticalScrollBar,
    bool SuppressInternalScrollBarValueChange,
    int InputScrollMutationDepth,
    float ContentViewportX,
    float ContentViewportY,
    float ContentViewportWidth,
    float ContentViewportHeight,
    string ResolveBarsAndMeasureContentLastTrace,
    string ResolveBarsAndMeasureContentHottestTrace,
    double ResolveBarsAndMeasureContentHottestMilliseconds,
    int WheelEvents,
    int WheelHandled,
    int SetOffsetCalls,
    int SetOffsetNoOpCalls,
    float TotalHorizontalDelta,
    float TotalVerticalDelta,
    int ScrollToHorizontalOffsetCallCount,
    int ScrollToVerticalOffsetCallCount,
    int InvalidateScrollInfoCallCount,
    int HandleMouseWheelCallCount,
    double HandleMouseWheelMilliseconds,
    int HandleMouseWheelHandledCount,
    int HandleMouseWheelIgnoredDisabledCount,
    int HandleMouseWheelIgnoredZeroDeltaCount,
    double SetOffsetsMilliseconds,
    int SetOffsetsExternalSourceCount,
    int SetOffsetsHorizontalScrollBarSourceCount,
    int SetOffsetsVerticalScrollBarSourceCount,
    int SetOffsetsWorkCount,
    int SetOffsetsDeferredLayoutPathCount,
    int SetOffsetsVirtualizingMeasureInvalidationPathCount,
    int SetOffsetsVirtualizingArrangeOnlyPathCount,
    int SetOffsetsTransformInvalidationPathCount,
    int SetOffsetsManualArrangePathCount,
    int PopupCloseCallCount,
    int ArrangeContentForCurrentOffsetsCallCount,
    double ArrangeContentForCurrentOffsetsMilliseconds,
    int ArrangeContentSkippedNoContentCount,
    int ArrangeContentSkippedZeroViewportCount,
    int ArrangeContentTransformPathCount,
    int ArrangeContentOffsetPathCount,
    int UpdateScrollBarValuesCallCount,
    double UpdateScrollBarValuesMilliseconds,
    int UpdateHorizontalScrollBarValueCallCount,
    double UpdateHorizontalScrollBarValueMilliseconds,
    int UpdateVerticalScrollBarValueCallCount,
    double UpdateVerticalScrollBarValueMilliseconds,
    int HorizontalValueChangedCallCount,
    double HorizontalValueChangedMilliseconds,
    double HorizontalValueChangedSetOffsetsMilliseconds,
    int HorizontalValueChangedSuppressedCount,
    int VerticalValueChangedCallCount,
    double VerticalValueChangedMilliseconds,
    double VerticalValueChangedSetOffsetsMilliseconds,
    int VerticalValueChangedSuppressedCount,
    int MeasureOverrideCallCount,
    double MeasureOverrideMilliseconds,
    int ArrangeOverrideCallCount,
    double ArrangeOverrideMilliseconds,
    int ResolveBarsAndMeasureContentCallCount,
    double ResolveBarsAndMeasureContentMilliseconds,
    int ResolveBarsAndMeasureContentIterationCount,
    int ResolveBarsAndMeasureContentHorizontalFlipCount,
    int ResolveBarsAndMeasureContentVerticalFlipCount,
    int ResolveBarsAndMeasureContentSingleMeasurePathCount,
    int ResolveBarsAndMeasureContentRemeasurePathCount,
    int ResolveBarsAndMeasureContentFallbackCount,
    int ResolveBarsAndMeasureContentInitialHorizontalVisibleCount,
    int ResolveBarsAndMeasureContentInitialHorizontalHiddenCount,
    int ResolveBarsAndMeasureContentInitialVerticalVisibleCount,
    int ResolveBarsAndMeasureContentInitialVerticalHiddenCount,
    int ResolveBarsAndMeasureContentResolvedHorizontalVisibleCount,
    int ResolveBarsAndMeasureContentResolvedHorizontalHiddenCount,
    int ResolveBarsAndMeasureContentResolvedVerticalVisibleCount,
    int ResolveBarsAndMeasureContentResolvedVerticalHiddenCount,
    int ResolveBarsForArrangeCallCount,
    double ResolveBarsForArrangeMilliseconds,
    int ResolveBarsForArrangeIterationCount,
    int ResolveBarsForArrangeHorizontalFlipCount,
    int ResolveBarsForArrangeVerticalFlipCount,
    int MeasureContentCallCount,
    double MeasureContentMilliseconds,
    int UpdateScrollBarsCallCount,
    double UpdateScrollBarsMilliseconds)
{
    public int SetOffsetsCallCount => SetOffsetCalls;

    public int SetOffsetsNoOpCount => SetOffsetNoOpCalls;
}

/// <summary>
/// ScrollBar thumb drag telemetry snapshot.
/// </summary>
internal readonly record struct ScrollBarThumbDragTelemetrySnapshot(
    int OnThumbDragDeltaCallCount,
    double OnThumbDragDeltaMilliseconds,
    double OnThumbDragDeltaValueSetMilliseconds,
    double OnValueChangedBaseMilliseconds,
    double OnValueChangedSyncTrackStateMilliseconds,
    double SyncTrackStateMilliseconds,
    double RefreshTrackLayoutMilliseconds);

/// <summary>
/// Track thumb travel telemetry snapshot.
/// </summary>
internal readonly record struct TrackThumbTravelTelemetrySnapshot(
    int GetValueFromThumbTravelCallCount,
    double GetValueFromThumbTravelMilliseconds,
    int RefreshLayoutForStateMutationCallCount,
    double RefreshLayoutForStateMutationMilliseconds,
    int RefreshLayoutValueMutationCallCount,
    double RefreshLayoutValueMutationMilliseconds,
    int RefreshLayoutViewportMutationCallCount,
    double RefreshLayoutViewportMutationMilliseconds,
    int RefreshLayoutMinimumMutationCallCount,
    double RefreshLayoutMinimumMutationMilliseconds,
    int RefreshLayoutMaximumMutationCallCount,
    double RefreshLayoutMaximumMutationMilliseconds,
    int RefreshLayoutDirectionMutationCallCount,
    double RefreshLayoutDirectionMutationMilliseconds,
    int RefreshLayoutNeedsMeasureFallbackCount,
    double RefreshLayoutNeedsMeasureFallbackMilliseconds,
    double RefreshLayoutCaptureSnapshotMilliseconds,
    double RefreshLayoutInvalidateArrangeMilliseconds,
    double RefreshLayoutArrangeMilliseconds,
    double RefreshLayoutDirtyBoundsMilliseconds,
    int RefreshLayoutDirtyBoundsHintCount,
    int RefreshLayoutVisualFallbackCount,
    double RefreshLayoutVisualInvalidationMilliseconds);
