using System;
using System.Collections.Generic;
using System.Diagnostics;
using InkkSlinger.UI.Telemetry;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace InkkSlinger;

public partial class ScrollViewer
{
    private ScrollBar _horizontalBar;
    private ScrollBar _verticalBar;
    private ScrollContentPresenter? _templateContentPresenter;
    private readonly ScrollViewerContentPresenter _contentPresenter;
    private readonly Queue<ScrollCommand> _scrollCommandQueue = new();
    internal LayoutRect _contentViewportRect;
    private bool _hasSyncedScrollBarState;
    private float _lastSyncedHorizontalViewportSize;
    private float _lastSyncedVerticalViewportSize;
    private float _lastSyncedHorizontalMaximum;
    private float _lastSyncedVerticalMaximum;
    private float _lastSyncedHorizontalLargeChange;
    private float _lastSyncedVerticalLargeChange;
    private float _lastSyncedHorizontalValue;
    private float _lastSyncedVerticalValue;
    private bool _showHorizontalBar;
    private bool _showVerticalBar;
    internal bool _hasPreviousScrollBarResolution;
    private bool _previousShowHorizontalScrollBar;
    private bool _previousShowVerticalScrollBar;
    private bool _isReconcilingDescendantMeasureInvalidation;
    private bool _isPointerPanning;
    private Vector2 _lastPointerPanPosition;
    private int _inputScrollMutationDepth;
    private bool _suppressInternalScrollBarValueChange;
    private bool _suppressOffsetPropertyChange;
    private bool _isExecutingScrollCommandQueue;
    private int _runtimeMeasureOverrideCallCount;
    private long _runtimeMeasureOverrideElapsedTicks;
    private int _runtimeArrangeOverrideCallCount;
    private long _runtimeArrangeOverrideElapsedTicks;
    private int _runtimeResolveBarsAndMeasureContentCallCount;
    private long _runtimeResolveBarsAndMeasureContentElapsedTicks;
    private int _runtimeResolveBarsAndMeasureContentIterationCount;
    private int _runtimeResolveBarsAndMeasureContentHorizontalFlipCount;
    private int _runtimeResolveBarsAndMeasureContentVerticalFlipCount;
    private int _runtimeResolveBarsAndMeasureContentSingleMeasurePathCount;
    private int _runtimeResolveBarsAndMeasureContentRemeasurePathCount;
    private int _runtimeResolveBarsAndMeasureContentFallbackCount;
    private int _runtimeResolveBarsAndMeasureContentInitialHorizontalVisibleCount;
    private int _runtimeResolveBarsAndMeasureContentInitialHorizontalHiddenCount;
    private int _runtimeResolveBarsAndMeasureContentInitialVerticalVisibleCount;
    private int _runtimeResolveBarsAndMeasureContentInitialVerticalHiddenCount;
    private int _runtimeResolveBarsAndMeasureContentResolvedHorizontalVisibleCount;
    private int _runtimeResolveBarsAndMeasureContentResolvedHorizontalHiddenCount;
    private int _runtimeResolveBarsAndMeasureContentResolvedVerticalVisibleCount;
    private int _runtimeResolveBarsAndMeasureContentResolvedVerticalHiddenCount;
    private long _runtimeResolveBarsAndMeasureContentHottestTicks;
    private string _runtimeResolveBarsAndMeasureContentLastTrace = "n/a";
    private string _runtimeResolveBarsAndMeasureContentHottestTrace = "n/a";
    private int _runtimeResolveBarsForArrangeCallCount;
    private long _runtimeResolveBarsForArrangeElapsedTicks;
    private int _runtimeResolveBarsForArrangeIterationCount;
    private int _runtimeResolveBarsForArrangeHorizontalFlipCount;
    private int _runtimeResolveBarsForArrangeVerticalFlipCount;
    internal int _runtimeMeasureContentCallCount;
    internal long _runtimeMeasureContentElapsedTicks;
    private int _runtimeUpdateScrollBarsCallCount;
    private long _runtimeUpdateScrollBarsElapsedTicks;
    private int _runtimeScrollToHorizontalOffsetCallCount;
    private int _runtimeScrollToVerticalOffsetCallCount;
    private int _runtimeInvalidateScrollInfoCallCount;
    private int _runtimeHandleMouseWheelCallCount;
    private long _runtimeHandleMouseWheelElapsedTicks;
    private int _runtimeWheelEvents;
    private int _runtimeWheelHandled;
    private int _runtimeHandleMouseWheelHandledCount;
    private int _runtimeHandleMouseWheelIgnoredDisabledCount;
    private int _runtimeHandleMouseWheelIgnoredZeroDeltaCount;
    private int _runtimeSetOffsetsCallCount;
    private long _runtimeSetOffsetsElapsedTicks;
    private float _runtimeHorizontalDelta;
    private float _runtimeVerticalDelta;
    private int _runtimeSetOffsetsExternalSourceCount;
    private int _runtimeSetOffsetsHorizontalScrollBarSourceCount;
    private int _runtimeSetOffsetsVerticalScrollBarSourceCount;
    private int _runtimeSetOffsetsWorkCount;
    private int _runtimeSetOffsetsNoOpCount;
    private int _runtimeSetOffsetsDeferredLayoutPathCount;
    private int _runtimeSetOffsetsVirtualizingMeasureInvalidationPathCount;
    private int _runtimeSetOffsetsVirtualizingArrangeOnlyPathCount;
    private int _runtimeSetOffsetsTransformInvalidationPathCount;
    private int _runtimeSetOffsetsManualArrangePathCount;
    private int _runtimePopupCloseCallCount;
    internal int _runtimeArrangeContentForCurrentOffsetsCallCount;
    internal long _runtimeArrangeContentForCurrentOffsetsElapsedTicks;
    internal int _runtimeArrangeContentSkippedNoContentCount;
    internal int _runtimeArrangeContentSkippedZeroViewportCount;
    internal int _runtimeArrangeContentTransformPathCount;
    internal int _runtimeArrangeContentOffsetPathCount;
    private int _runtimeUpdateScrollBarValuesCallCount;
    private long _runtimeUpdateScrollBarValuesElapsedTicks;
    private int _runtimeUpdateHorizontalScrollBarValueCallCount;
    private long _runtimeUpdateHorizontalScrollBarValueElapsedTicks;
    private int _runtimeUpdateVerticalScrollBarValueCallCount;
    private long _runtimeUpdateVerticalScrollBarValueElapsedTicks;
    private int _runtimeHorizontalValueChangedCallCount;
    private long _runtimeHorizontalValueChangedElapsedTicks;
    private long _runtimeHorizontalValueChangedSetOffsetsElapsedTicks;
    private int _runtimeHorizontalValueChangedSuppressedCount;
    private int _runtimeVerticalValueChangedCallCount;
    private long _runtimeVerticalValueChangedElapsedTicks;
    private long _runtimeVerticalValueChangedSetOffsetsElapsedTicks;
    private int _lastTransformScrollDirtyHintDrawCount = -1;
    private int _runtimeVerticalValueChangedSuppressedCount;
    private static int _diagWheelEvents;
    private static int _diagWheelHandled;
    private static int _diagSetOffsetCalls;
    private static int _diagSetOffsetNoOp;
    private static float _diagVerticalDelta;
    private static float _diagHorizontalDelta;
    private static int _diagScrollToHorizontalOffsetCallCount;
    private static int _diagScrollToVerticalOffsetCallCount;
    private static int _diagInvalidateScrollInfoCallCount;
    private static int _diagHandleMouseWheelCallCount;
    private static long _diagHandleMouseWheelElapsedTicks;
    private static int _diagHandleMouseWheelHandledCount;
    private static int _diagHandleMouseWheelIgnoredDisabledCount;
    private static int _diagHandleMouseWheelIgnoredZeroDeltaCount;
    private static int _diagInteractionSetOffsetsCallCount;
    private static int _diagInteractionSetOffsetsNoOpCount;
    private static long _diagSetOffsetsElapsedTicks;
    private static int _diagSetOffsetsExternalSourceCount;
    private static int _diagSetOffsetsHorizontalScrollBarSourceCount;
    private static int _diagSetOffsetsVerticalScrollBarSourceCount;
    private static int _diagSetOffsetsWorkCount;
    private static int _diagSetOffsetsDeferredLayoutPathCount;
    private static int _diagSetOffsetsVirtualizingMeasureInvalidationPathCount;
    private static int _diagSetOffsetsVirtualizingArrangeOnlyPathCount;
    private static int _diagSetOffsetsTransformInvalidationPathCount;
    private static int _diagSetOffsetsManualArrangePathCount;
    private static int _diagPopupCloseCallCount;
    internal static int _diagArrangeContentForCurrentOffsetsCallCount;
    internal static long _diagArrangeContentForCurrentOffsetsElapsedTicks;
    internal static int _diagArrangeContentSkippedNoContentCount;
    internal static int _diagArrangeContentSkippedZeroViewportCount;
    internal static int _diagArrangeContentTransformPathCount;
    internal static int _diagArrangeContentOffsetPathCount;
    private static int _diagUpdateScrollBarValuesCallCount;
    private static long _diagUpdateScrollBarValuesElapsedTicks;
    private static int _diagUpdateHorizontalScrollBarValueCallCount;
    private static long _diagUpdateHorizontalScrollBarValueElapsedTicks;
    private static int _diagUpdateVerticalScrollBarValueCallCount;
    private static long _diagUpdateVerticalScrollBarValueElapsedTicks;
    private static int _diagHorizontalValueChangedCallCount;
    private static long _diagHorizontalValueChangedElapsedTicks;
    private static long _diagHorizontalValueChangedSetOffsetsElapsedTicks;
    private static int _diagHorizontalValueChangedSuppressedCount;
    private static int _diagVerticalValueChangedCallCount;
    private static long _diagVerticalValueChangedElapsedTicks;
    private static long _diagVerticalValueChangedSetOffsetsElapsedTicks;
    private static int _diagVerticalValueChangedSuppressedCount;
    private static int _diagMeasureOverrideCallCount;
    private static long _diagMeasureOverrideElapsedTicks;
    private static int _diagArrangeOverrideCallCount;
    private static long _diagArrangeOverrideElapsedTicks;
    private static int _diagResolveBarsAndMeasureContentCallCount;
    private static long _diagResolveBarsAndMeasureContentElapsedTicks;
    private static int _diagResolveBarsAndMeasureContentIterationCount;
    private static int _diagResolveBarsAndMeasureContentHorizontalFlipCount;
    private static int _diagResolveBarsAndMeasureContentVerticalFlipCount;
    private static int _diagResolveBarsAndMeasureContentSingleMeasurePathCount;
    private static int _diagResolveBarsAndMeasureContentRemeasurePathCount;
    private static int _diagResolveBarsAndMeasureContentFallbackCount;
    private static int _diagResolveBarsAndMeasureContentInitialHorizontalVisibleCount;
    private static int _diagResolveBarsAndMeasureContentInitialHorizontalHiddenCount;
    private static int _diagResolveBarsAndMeasureContentInitialVerticalVisibleCount;
    private static int _diagResolveBarsAndMeasureContentInitialVerticalHiddenCount;
    private static int _diagResolveBarsAndMeasureContentResolvedHorizontalVisibleCount;
    private static int _diagResolveBarsAndMeasureContentResolvedHorizontalHiddenCount;
    private static int _diagResolveBarsAndMeasureContentResolvedVerticalVisibleCount;
    private static int _diagResolveBarsAndMeasureContentResolvedVerticalHiddenCount;
    private static int _diagResolveBarsForArrangeCallCount;
    private static long _diagResolveBarsForArrangeElapsedTicks;
    private static int _diagResolveBarsForArrangeIterationCount;
    private static int _diagResolveBarsForArrangeHorizontalFlipCount;
    private static int _diagResolveBarsForArrangeVerticalFlipCount;
    internal static int _diagMeasureContentCallCount;
    internal static long _diagMeasureContentElapsedTicks;
    private static int _diagUpdateScrollBarsCallCount;
    private static long _diagUpdateScrollBarsElapsedTicks;
    private const float DefaultLineScrollStep = 24f;
}
