using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using Xunit;

namespace InkkSlinger.Tests;

public class DataGridCollectionViewTests
{
    [Fact]
    public void DataGrid_HeaderSortUpdatesCollectionViewSortDescriptions()
    {
        var source = new ObservableCollection<Row>
        {
            new(2, "B"),
            new(1, "A")
        };

        var grid = new DataGrid
        {
            ItemsSource = source
        };
        grid.Columns.Add(new DataGridColumn
        {
            Header = "Id",
            BindingPath = nameof(Row.Id)
        });

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        var headers = grid.ColumnHeadersForTesting;
        Assert.NotEmpty(headers);

        headers[0].RaiseRoutedEventInternal(Button.ClickEvent, new RoutedSimpleEventArgs(Button.ClickEvent));

        var view = Assert.IsAssignableFrom<ICollectionView>(typeof(ItemsControl)
            .GetProperty("ItemsSourceView", BindingFlags.Instance | BindingFlags.NonPublic)!
            .GetValue(grid));
        Assert.NotEmpty(view.SortDescriptions);
        Assert.Equal(nameof(Row.Id), view.SortDescriptions[0].PropertyName);
    }

    [Fact]
    public void DataGrid_AutoGeneratedHeaderSortDirection_PersistsAcrossViewRefresh()
    {
        var source = new ObservableCollection<Row>
        {
            new(2, "B"),
            new(1, "A")
        };

        var grid = new DataGrid
        {
            ItemsSource = source
        };

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        var headers = grid.ColumnHeadersForTesting;
        Assert.NotEmpty(headers);

        headers[0].RaiseRoutedEventInternal(Button.ClickEvent, new RoutedSimpleEventArgs(Button.ClickEvent));
        Assert.Equal(DataGridSortDirection.Ascending, headers[0].SortDirection);

        headers[0].RaiseRoutedEventInternal(Button.ClickEvent, new RoutedSimpleEventArgs(Button.ClickEvent));
        Assert.Equal(DataGridSortDirection.Descending, headers[0].SortDirection);

        var firstRow = Assert.IsType<DataGridRow>(grid.GetItemContainersForPresenter()[0]);
        Assert.Equal("2", firstRow.Cells[0].Value?.ToString());
        Assert.Equal("2", firstRow.Cells[0].Content?.ToString());
    }

    [Fact]
    public void DataGrid_ClickingDifferentColumn_ReplacesPreviousSort()
    {
        var source = new ObservableCollection<Row>
        {
            new(2, "A"),
            new(1, "B"),
            new(3, "A")
        };

        var grid = new DataGrid
        {
            ItemsSource = source
        };

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        var headers = grid.ColumnHeadersForTesting;
        Assert.Equal(2, headers.Count);

        var view = Assert.IsAssignableFrom<ICollectionView>(typeof(ItemsControl)
            .GetProperty("ItemsSourceView", BindingFlags.Instance | BindingFlags.NonPublic)!
            .GetValue(grid));

        var nameHeader = Assert.Single(headers, static header => header.GetContentText() == nameof(Row.Name));
        nameHeader.RaiseRoutedEventInternal(Button.ClickEvent, new RoutedSimpleEventArgs(Button.ClickEvent));
        Assert.Equal(DataGridSortDirection.Ascending, nameHeader.SortDirection);
        Assert.Single(view.SortDescriptions);
        Assert.Equal(nameof(Row.Name), view.SortDescriptions[0].PropertyName);

        var idHeader = Assert.Single(headers, static header => header.GetContentText() == nameof(Row.Id));
        idHeader.RaiseRoutedEventInternal(Button.ClickEvent, new RoutedSimpleEventArgs(Button.ClickEvent));

        Assert.Equal(DataGridSortDirection.None, nameHeader.SortDirection);
        Assert.Equal(DataGridSortDirection.Ascending, idHeader.SortDirection);
        Assert.Single(view.SortDescriptions);
        Assert.Equal(nameof(Row.Id), view.SortDescriptions[0].PropertyName);

        var firstRow = Assert.IsType<DataGridRow>(grid.GetItemContainersForPresenter()[0]);
        Assert.Equal("1", firstRow.Cells[0].Value?.ToString());
        Assert.Equal("B", firstRow.Cells[1].Value?.ToString());
    }

    [Fact]
    public void DataGrid_ThirdHeaderClick_ClearsSort()
    {
        var source = new ObservableCollection<Row>
        {
            new(2, "B"),
            new(1, "A")
        };

        var grid = new DataGrid
        {
            ItemsSource = source
        };

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        var header = Assert.Single(grid.ColumnHeadersForTesting, static item => item.GetContentText() == nameof(Row.Id));
        var view = Assert.IsAssignableFrom<ICollectionView>(typeof(ItemsControl)
            .GetProperty("ItemsSourceView", BindingFlags.Instance | BindingFlags.NonPublic)!
            .GetValue(grid));

        header.RaiseRoutedEventInternal(Button.ClickEvent, new RoutedSimpleEventArgs(Button.ClickEvent));
        header.RaiseRoutedEventInternal(Button.ClickEvent, new RoutedSimpleEventArgs(Button.ClickEvent));
        header.RaiseRoutedEventInternal(Button.ClickEvent, new RoutedSimpleEventArgs(Button.ClickEvent));

        Assert.Equal(DataGridSortDirection.None, header.SortDirection);
        Assert.Empty(view.SortDescriptions);
    }

    [Fact]
    public void DataGrid_ShiftClickingHeader_AppendsSortDescription()
    {
        var source = new ObservableCollection<Row>
        {
            new(2, "B"),
            new(1, "A"),
            new(3, "A")
        };

        var grid = new DataGrid
        {
            ItemsSource = source,
            Width = 600,
            Height = 400
        };

        var host = new Canvas { Width = 640f, Height = 440f };
        host.AddChild(grid);
        var uiRoot = new UiRoot(host);
        uiRoot.Update(new Microsoft.Xna.Framework.GameTime(System.TimeSpan.FromMilliseconds(16), System.TimeSpan.FromMilliseconds(16)), new Microsoft.Xna.Framework.Graphics.Viewport(0, 0, 640, 440));

        var headers = grid.ColumnHeadersForTesting;
        var nameHeader = Assert.Single(headers, static header => header.GetContentText() == nameof(Row.Name));
        var idHeader = Assert.Single(headers, static header => header.GetContentText() == nameof(Row.Id));

        Assert.True(grid.HandlePointerDownFromInput(nameHeader, GetCenter(nameHeader.LayoutSlot), ModifierKeys.None, out _));
        Assert.True(grid.HandlePointerUpFromInput(GetCenter(nameHeader.LayoutSlot)));

        Assert.True(grid.HandlePointerDownFromInput(idHeader, GetCenter(idHeader.LayoutSlot), ModifierKeys.Shift, out _));
        Assert.True(grid.HandlePointerUpFromInput(GetCenter(idHeader.LayoutSlot)));

        var view = Assert.IsAssignableFrom<ICollectionView>(typeof(ItemsControl)
            .GetProperty("ItemsSourceView", BindingFlags.Instance | BindingFlags.NonPublic)!
            .GetValue(grid));

        Assert.Equal(2, view.SortDescriptions.Count);
        Assert.Equal(nameof(Row.Name), view.SortDescriptions[0].PropertyName);
        Assert.Equal(nameof(Row.Id), view.SortDescriptions[1].PropertyName);
    }

    [Fact]
    public void DataGrid_HeaderSort_ReusesExistingRowContainers()
    {
        var source = new ObservableCollection<Row>
        {
            new(2, "Bravo"),
            new(1, "Alpha"),
            new(3, "Charlie")
        };

        var grid = new DataGrid
        {
            ItemsSource = source
        };

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        var rowsBefore = grid.RowsForTesting.ToArray();
        var header = Assert.Single(grid.ColumnHeadersForTesting, static item => item.GetContentText() == nameof(Row.Name));

        header.RaiseRoutedEventInternal(Button.ClickEvent, new RoutedSimpleEventArgs(Button.ClickEvent));

        var rowsAfter = grid.RowsForTesting.ToArray();
        Assert.Equal(rowsBefore.Length, rowsAfter.Length);
        Assert.Same(rowsBefore[1], rowsAfter[0]);
        Assert.Same(rowsBefore[0], rowsAfter[1]);
        Assert.Same(rowsBefore[2], rowsAfter[2]);
        Assert.Same(source[1], rowsAfter[0].Item);
        Assert.Same(source[0], rowsAfter[1].Item);
        Assert.Same(source[2], rowsAfter[2].Item);
    }

    [Fact]
    public void DataGrid_ItemPropertyChange_UpdatesVisibleCellWithoutRebuildingRow()
    {
        var source = new ObservableCollection<ObservableRow>
        {
            new(1, "Alpha")
        };

        var grid = new DataGrid
        {
            ItemsSource = source
        };

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        var originalRow = Assert.IsType<DataGridRow>(grid.GetItemContainersForPresenter()[0]);
        var originalCell = originalRow.Cells[1];
        Assert.Equal("Alpha", originalCell.Content?.ToString());

        source[0].Name = "Updated";

        var currentRow = Assert.IsType<DataGridRow>(grid.GetItemContainersForPresenter()[0]);
        Assert.Same(originalRow, currentRow);
        Assert.Same(originalCell, currentRow.Cells[1]);
        Assert.Equal("Updated", currentRow.Cells[1].Content?.ToString());
        Assert.Equal("Updated", currentRow.Cells[1].Value?.ToString());
    }

    [Fact]
    public void DataGrid_ChangingItemsSource_RebuildsAutoGeneratedHeadersWithoutStaleState()
    {
        var firstSource = new ObservableCollection<Row>
        {
            new(1, "Alpha")
        };
        var secondSource = new ObservableCollection<OtherRow>
        {
            new("A1", true)
        };

        var grid = new DataGrid
        {
            ItemsSource = firstSource
        };

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        Assert.Equal(new[] { nameof(Row.Id), nameof(Row.Name) }, grid.ColumnHeadersForTesting.Select(static header => header.GetContentText()));

        grid.ItemsSource = secondSource;
        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        Assert.Equal(new[] { nameof(OtherRow.Code), nameof(OtherRow.Enabled) }, grid.ColumnHeadersForTesting.Select(static header => header.GetContentText()));
        var firstRow = Assert.IsType<DataGridRow>(grid.GetItemContainersForPresenter()[0]);
        Assert.Equal("A1", firstRow.Cells[0].Content?.ToString());
        Assert.Equal("True", firstRow.Cells[1].Content?.ToString());
    }

    [Fact]
    public void DataGrid_AutoGenerateColumnsFalse_DoesNotCreateGeneratedHeaders()
    {
        var source = new ObservableCollection<Row>
        {
            new(1, "Alpha")
        };

        var grid = new DataGrid
        {
            ItemsSource = source,
            AutoGenerateColumns = false
        };

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        Assert.Empty(grid.ColumnHeadersForTesting);
        var firstRow = Assert.IsType<DataGridRow>(grid.GetItemContainersForPresenter()[0]);
        Assert.Empty(firstRow.Cells);
    }

    [Fact]
    public void DataGrid_AutoGeneratingColumn_CanCancelGeneratedColumn()
    {
        var source = new ObservableCollection<Row>
        {
            new(1, "Alpha")
        };

        var grid = new DataGrid();
        var autoGeneratedRaised = false;
        grid.AutoGeneratingColumn += static (_, args) =>
        {
            if (args.PropertyName == nameof(Row.Name))
            {
                args.Cancel = true;
            }
        };
        grid.AutoGeneratedColumns += (_, _) => autoGeneratedRaised = true;
        grid.ItemsSource = source;

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        Assert.True(autoGeneratedRaised);
        Assert.Equal(new[] { nameof(Row.Id) }, grid.ColumnHeadersForTesting.Select(static header => header.GetContentText()));
    }

    private sealed record Row(int Id, string Name);

    private sealed record OtherRow(string Code, bool Enabled);

    private sealed class ObservableRow : INotifyPropertyChanged
    {
        private string _name;

        public ObservableRow(int id, string name)
        {
            Id = id;
            _name = name;
        }

        public event PropertyChangedEventHandler? PropertyChanged;

        public int Id { get; }

        public string Name
        {
            get => _name;
            set
            {
                if (_name == value)
                {
                    return;
                }

                _name = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Name)));
            }
        }
    }

    private static Microsoft.Xna.Framework.Vector2 GetCenter(LayoutRect rect)
    {
        return new Microsoft.Xna.Framework.Vector2(rect.X + (rect.Width / 2f), rect.Y + (rect.Height / 2f));
    }
}
