using System.Collections.ObjectModel;
using System.Reflection;
using Xunit;

namespace InkkSlinger.Tests;

public class DataGridCollectionViewTests
{
    [Fact]
    public void DataGrid_HeaderSortUpdatesCollectionViewSortDescriptions()
    {
        var source = new ObservableCollection<Row>
        {
            new(2, "B"),
            new(1, "A")
        };

        var grid = new DataGrid
        {
            ItemsSource = source
        };
        grid.Columns.Add(new DataGridColumn
        {
            Header = "Id",
            BindingPath = nameof(Row.Id)
        });

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        var headersField = typeof(DataGrid).GetField("_columnHeaders", BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(headersField);
        var headers = Assert.IsType<System.Collections.Generic.List<DataGridColumnHeader>>(headersField!.GetValue(grid));
        Assert.NotEmpty(headers);

        var invoke = typeof(DataGrid).GetMethod("OnColumnHeaderClick", BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(invoke);
        invoke!.Invoke(grid, [headers[0], new RoutedSimpleEventArgs(Button.ClickEvent)]);

        var view = Assert.IsAssignableFrom<ICollectionView>(typeof(ItemsControl)
            .GetProperty("ItemsSourceView", BindingFlags.Instance | BindingFlags.NonPublic)!
            .GetValue(grid));
        Assert.NotEmpty(view.SortDescriptions);
        Assert.Equal(nameof(Row.Id), view.SortDescriptions[0].PropertyName);
    }

    [Fact]
    public void DataGrid_AutoGeneratedHeaderSortDirection_PersistsAcrossViewRefresh()
    {
        var source = new ObservableCollection<Row>
        {
            new(2, "B"),
            new(1, "A")
        };

        var grid = new DataGrid
        {
            ItemsSource = source
        };

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        var headersField = typeof(DataGrid).GetField("_columnHeaders", BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(headersField);
        var headers = Assert.IsType<System.Collections.Generic.List<DataGridColumnHeader>>(headersField!.GetValue(grid));
        Assert.NotEmpty(headers);

        var invoke = typeof(DataGrid).GetMethod("OnColumnHeaderClick", BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(invoke);

        invoke!.Invoke(grid, [headers[0], new RoutedSimpleEventArgs(Button.ClickEvent)]);
        Assert.Equal(DataGridSortDirection.Ascending, headers[0].SortDirection);

        invoke.Invoke(grid, [headers[0], new RoutedSimpleEventArgs(Button.ClickEvent)]);
        Assert.Equal(DataGridSortDirection.Descending, headers[0].SortDirection);

        var firstRow = Assert.IsType<DataGridRow>(grid.GetItemContainersForPresenter()[0]);
        Assert.Equal("2", firstRow.Cells[0].Value?.ToString());
    }

    [Fact]
    public void DataGrid_ClickingDifferentColumn_ReplacesPreviousSort()
    {
        var source = new ObservableCollection<Row>
        {
            new(2, "A"),
            new(1, "B"),
            new(3, "A")
        };

        var grid = new DataGrid
        {
            ItemsSource = source
        };

        grid.Measure(new Microsoft.Xna.Framework.Vector2(600, 400));
        grid.Arrange(new LayoutRect(0, 0, 600, 400));

        var headersField = typeof(DataGrid).GetField("_columnHeaders", BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(headersField);
        var headers = Assert.IsType<System.Collections.Generic.List<DataGridColumnHeader>>(headersField!.GetValue(grid));
        Assert.Equal(2, headers.Count);

        var view = Assert.IsAssignableFrom<ICollectionView>(typeof(ItemsControl)
            .GetProperty("ItemsSourceView", BindingFlags.Instance | BindingFlags.NonPublic)!
            .GetValue(grid));
        var invoke = typeof(DataGrid).GetMethod("OnColumnHeaderClick", BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(invoke);

        var nameHeader = Assert.Single(headers, static header => header.Text == nameof(Row.Name));
        invoke!.Invoke(grid, [nameHeader, new RoutedSimpleEventArgs(Button.ClickEvent)]);
        Assert.Equal(DataGridSortDirection.Ascending, nameHeader.SortDirection);
        Assert.Single(view.SortDescriptions);
        Assert.Equal(nameof(Row.Name), view.SortDescriptions[0].PropertyName);

        var idHeader = Assert.Single(headers, static header => header.Text == nameof(Row.Id));
        invoke.Invoke(grid, [idHeader, new RoutedSimpleEventArgs(Button.ClickEvent)]);

        Assert.Equal(DataGridSortDirection.None, nameHeader.SortDirection);
        Assert.Equal(DataGridSortDirection.Ascending, idHeader.SortDirection);
        Assert.Single(view.SortDescriptions);
        Assert.Equal(nameof(Row.Id), view.SortDescriptions[0].PropertyName);

        var firstRow = Assert.IsType<DataGridRow>(grid.GetItemContainersForPresenter()[0]);
        Assert.Equal("1", firstRow.Cells[0].Value?.ToString());
        Assert.Equal("B", firstRow.Cells[1].Value?.ToString());
    }

    private sealed record Row(int Id, string Name);
}
