namespace InkkSlinger.UI.Telemetry;

public readonly record struct DesignerSourceEditorViewTelemetrySnapshot(
    long SourceEditorTextChangedCallCount,
    double SourceEditorTextChangedMilliseconds,
    long SourceEditorTextChangedRefreshHighlightedCallCount,
    double SourceEditorTextChangedRefreshHighlightedMilliseconds,
    long SourceEditorTextChangedRefreshPropertyInspectorCallCount,
    double SourceEditorTextChangedRefreshPropertyInspectorMilliseconds,
    long SourceEditorTextChangedRefreshCompletionCallCount,
    double SourceEditorTextChangedRefreshCompletionMilliseconds,
    long SourceTextChangedCallCount,
    double SourceTextChangedMilliseconds,
    long RefreshHighlightedSourceDocumentCallCount,
    double RefreshHighlightedSourceDocumentMilliseconds,
    double RefreshHighlightedSourceDocumentOverviewMilliseconds,
    double RefreshHighlightedSourceDocumentDisplayTextMilliseconds,
    double RefreshHighlightedSourceDocumentUpdatePresentationMilliseconds,
    double RefreshHighlightedSourceDocumentSyntaxPopulateMilliseconds,
    double RefreshHighlightedSourceDocumentRestoreStateMilliseconds);

public readonly record struct DesignerSourceEditorViewRuntimeDiagnosticsSnapshot(
    long SourceEditorTextChangedCallCount,
    double SourceEditorTextChangedMilliseconds,
    long SourceEditorTextChangedRefreshHighlightedCallCount,
    double SourceEditorTextChangedRefreshHighlightedMilliseconds,
    long SourceEditorTextChangedRefreshPropertyInspectorCallCount,
    double SourceEditorTextChangedRefreshPropertyInspectorMilliseconds,
    long SourceEditorTextChangedRefreshCompletionCallCount,
    double SourceEditorTextChangedRefreshCompletionMilliseconds,
    double LastSourceEditorTextChangedMilliseconds,
    bool LastSourceEditorTextChangedRefreshedHighlighted,
    double LastSourceEditorTextChangedRefreshHighlightedMilliseconds,
    double LastSourceEditorTextChangedRefreshPropertyInspectorMilliseconds,
    bool LastSourceEditorTextChangedRefreshedCompletion,
    double LastSourceEditorTextChangedRefreshCompletionMilliseconds,
    long SourceTextChangedCallCount,
    double SourceTextChangedMilliseconds,
    double LastSourceTextChangedMilliseconds,
    long RefreshHighlightedSourceDocumentCallCount,
    double RefreshHighlightedSourceDocumentMilliseconds,
    double LastRefreshHighlightedSourceDocumentMilliseconds,
    double LastRefreshHighlightedSourceDocumentOverviewMilliseconds,
    double LastRefreshHighlightedSourceDocumentDisplayTextMilliseconds,
    double LastRefreshHighlightedSourceDocumentUpdatePresentationMilliseconds,
    double LastRefreshHighlightedSourceDocumentSyntaxPopulateMilliseconds,
    double LastRefreshHighlightedSourceDocumentRestoreStateMilliseconds,
    int LastRefreshHighlightedSourceDocumentTextLength);
