namespace InkkSlinger.UI.Telemetry;

internal readonly record struct IDEEditorTelemetrySnapshot(
    int UpdateLineNumberGutterCallCount,
    int UpdateLineNumberGutterForcedCount,
    int UpdateLineNumberGutterAppliedCount,
    int UpdateLineNumberGutterNoOpCount,
    int UpdateLineNumberGutterVisibleLineTotal,
    double UpdateLineNumberGutterMilliseconds,
    int EditorTextChangedCallCount,
    double EditorTextChangedMilliseconds,
    double EditorTextChangedUpdateCachedLineCountMilliseconds,
    double EditorTextChangedUpdateLineNumberGutterMilliseconds,
    double EditorTextChangedLineNumberPresenterUpdateMilliseconds,
    double EditorTextChangedLineNumberPresenterMeasureMilliseconds,
    double EditorTextChangedLineNumberPresenterArrangeMilliseconds,
    double EditorTextChangedIndentInvalidateMilliseconds,
    double EditorTextChangedSubscriberMilliseconds,
    int EditorDocumentChangedCallCount,
    int EditorViewportChangedCallCount,
    int EditorLayoutUpdatedCallCount,
    int IndentGuideInvalidateVisualCallCount,
    int BuildIndentGuideSnapshotCallCount,
    int BuildIndentGuideSnapshotSuccessCount,
    int BuildIndentGuideSnapshotSegmentTotal,
    double BuildIndentGuideSnapshotMilliseconds);

internal readonly record struct IDEEditorRuntimeDiagnosticsSnapshot(
    int UpdateLineNumberGutterCallCount,
    int UpdateLineNumberGutterForcedCount,
    int UpdateLineNumberGutterAppliedCount,
    int UpdateLineNumberGutterNoOpCount,
    int UpdateLineNumberGutterVisibleLineTotal,
    double UpdateLineNumberGutterMilliseconds,
    int EditorTextChangedCallCount,
    double EditorTextChangedMilliseconds,
    double EditorTextChangedUpdateCachedLineCountMilliseconds,
    double EditorTextChangedUpdateLineNumberGutterMilliseconds,
    double EditorTextChangedLineNumberPresenterUpdateMilliseconds,
    double EditorTextChangedLineNumberPresenterMeasureMilliseconds,
    double EditorTextChangedLineNumberPresenterArrangeMilliseconds,
    double EditorTextChangedIndentInvalidateMilliseconds,
    double EditorTextChangedSubscriberMilliseconds,
    double LastEditorTextChangedMilliseconds,
    double LastEditorTextChangedUpdateCachedLineCountMilliseconds,
    double LastEditorTextChangedUpdateLineNumberGutterMilliseconds,
    double LastEditorTextChangedLineNumberPresenterUpdateMilliseconds,
    double LastEditorTextChangedLineNumberPresenterMeasureMilliseconds,
    double LastEditorTextChangedLineNumberPresenterArrangeMilliseconds,
    double LastEditorTextChangedIndentInvalidateMilliseconds,
    double LastEditorTextChangedSubscriberMilliseconds,
    int EditorDocumentChangedCallCount,
    int EditorViewportChangedCallCount,
    int EditorLayoutUpdatedCallCount,
    int IndentGuideInvalidateVisualCallCount,
    int BuildIndentGuideSnapshotCallCount,
    int BuildIndentGuideSnapshotSuccessCount,
    int BuildIndentGuideSnapshotSegmentTotal,
    double BuildIndentGuideSnapshotMilliseconds,
    int CachedLineCount,
    int LastRenderedLineCount,
    int LastRenderedFirstVisibleLine,
    int LastRenderedVisibleLineCount,
    float LastRenderedLineOffset,
    float LastRenderedLineHeight,
    float HorizontalOffset,
    float VerticalOffset,
    float ViewportWidth,
    float ViewportHeight,
    float ExtentWidth,
    float ExtentHeight);

internal readonly record struct IDEEditorLineNumberPresenterTelemetrySnapshot(
    int UpdateVisibleRangeCallCount,
    int UpdateVisibleRangeChangedCount,
    int UpdateVisibleRangeTextUpdateCount,
    int UpdateVisibleRangeVisibleLineTotal,
    double UpdateVisibleRangeMilliseconds,
    int MeasureOverrideCallCount,
    double MeasureOverrideMilliseconds,
    int ArrangeOverrideCallCount,
    double ArrangeOverrideMilliseconds);

internal readonly record struct IDEEditorLineNumberPresenterRuntimeDiagnosticsSnapshot(
    int UpdateVisibleRangeCallCount,
    int UpdateVisibleRangeChangedCount,
    int UpdateVisibleRangeTextUpdateCount,
    int UpdateVisibleRangeVisibleLineTotal,
    double UpdateVisibleRangeMilliseconds,
    int MeasureOverrideCallCount,
    double MeasureOverrideMilliseconds,
    int ArrangeOverrideCallCount,
    double ArrangeOverrideMilliseconds,
    int FirstVisibleLine,
    int VisibleLineCount,
    float LineHeight,
    float VerticalLineOffset);

internal readonly record struct IDEEditorIndentGuideOverlayTelemetrySnapshot(
    int RenderCallCount,
    int RenderSkippedNoOwnerCount,
    int RenderSkippedEmptySnapshotCount,
    int RenderSegmentTotal,
    double RenderMilliseconds);

internal readonly record struct IDEEditorIndentGuideOverlayRuntimeDiagnosticsSnapshot(
    int RenderCallCount,
    int RenderSkippedNoOwnerCount,
    int RenderSkippedEmptySnapshotCount,
    int RenderSegmentTotal,
    double RenderMilliseconds,
    bool HasOwner);