using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Xml;
using InkkSlinger;
using Microsoft.Xna.Framework;

var outputPath = GetOutputPath(args);
Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);

var generator = new XamlSchemaGenerator();
generator.Generate(outputPath);

Console.WriteLine($"Wrote XAML schema to '{outputPath}'.");

return;

static string GetOutputPath(string[] args)
{
    for (var index = 0; index < args.Length - 1; index++)
    {
        if (string.Equals(args[index], "--output", StringComparison.OrdinalIgnoreCase))
        {
            return Path.GetFullPath(args[index + 1]);
        }
    }

    var repoRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", ".."));
    return Path.Combine(repoRoot, "InkkSlinger.UI", "Schemas", "InkkSlinger.UI.xsd");
}

internal sealed class XamlSchemaGenerator
{
    private static readonly Assembly UiAssembly = typeof(UIElement).Assembly;
    private static readonly IReadOnlyDictionary<string, Type> AliasedElementTypes = new Dictionary<string, Type>(StringComparer.Ordinal)
    {
        ["Rectangle"] = typeof(RectangleShape),
        ["Ellipse"] = typeof(EllipseShape),
        ["Line"] = typeof(LineShape),
        ["Polygon"] = typeof(PolygonShape),
        ["Polyline"] = typeof(PolylineShape),
        ["Path"] = typeof(PathShape)
    };

    private static readonly IReadOnlyDictionary<Type, string> AliasedElementNames = AliasedElementTypes
        .ToDictionary(static pair => pair.Value, static pair => pair.Key);

    public void Generate(string outputPath)
    {
        PrimeStaticConstructors();

        var dependencyProperties = DependencyProperty.GetRegisteredProperties().ToArray();
        var attachedSetters = DiscoverAttachedSetters();
        var typeEntries = BuildSchemaEntries(dependencyProperties, attachedSetters);
        var enumTypes = CollectEnumTypes(typeEntries, dependencyProperties, attachedSetters);
        var propertyElements = BuildPropertyElements(typeEntries, dependencyProperties, attachedSetters);

        using var writer = XmlWriter.Create(outputPath, new XmlWriterSettings
        {
            Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
            Indent = true,
            NewLineChars = "\n",
            OmitXmlDeclaration = false
        });

        writer.WriteStartDocument();
        writer.WriteComment(" Auto-generated by tools/InkkSlinger.XamlSchemaGenerator. Edit the generator, not this file. ");
        writer.WriteStartElement("xs", "schema", "http://www.w3.org/2001/XMLSchema");
        writer.WriteAttributeString("targetNamespace", "urn:inkkslinger-ui");
        writer.WriteAttributeString("xmlns", "urn:inkkslinger-ui");
        writer.WriteAttributeString("elementFormDefault", "qualified");
        writer.WriteAttributeString("attributeFormDefault", "unqualified");

        WriteSimpleAliasTypes(writer);
        WriteEnumTypes(writer, enumTypes);
        WriteObjectLikeType(writer, "xamlObjectType");
        WriteObjectLikeType(writer, "xamlPropertyElementType");
        WriteSchemaTypes(writer, typeEntries);
        WritePropertyElementDeclarations(writer, propertyElements);
        WriteElementDeclarations(writer, typeEntries);

        writer.WriteEndElement();
        writer.WriteEndDocument();
    }

    private static void PrimeStaticConstructors()
    {
        foreach (var type in UiAssembly.GetTypes())
        {
            if (type.ContainsGenericParameters)
            {
                continue;
            }

            try
            {
                RuntimeHelpers.RunClassConstructor(type.TypeHandle);
            }
            catch
            {
            }
        }
    }

    private static IReadOnlyList<AttachedSetterEntry> DiscoverAttachedSetters()
    {
        var attachedSetters = new Dictionary<string, AttachedSetterEntry>(StringComparer.Ordinal);

        foreach (var type in UiAssembly.GetTypes())
        {
            foreach (var method in type.GetMethods(BindingFlags.Public | BindingFlags.Static))
            {
                if (!method.Name.StartsWith("Set", StringComparison.Ordinal) || method.ReturnType != typeof(void))
                {
                    continue;
                }

                var parameters = method.GetParameters();
                if (parameters.Length != 2)
                {
                    continue;
                }

                var propertyName = method.Name[3..];
                if (string.IsNullOrWhiteSpace(propertyName))
                {
                    continue;
                }

                var fullName = type.Name + "." + propertyName;
                attachedSetters.TryAdd(fullName, new AttachedSetterEntry(type, propertyName, parameters[0].ParameterType, parameters[1].ParameterType));
            }
        }

        return attachedSetters.Values.OrderBy(static entry => entry.FullName, StringComparer.Ordinal).ToArray();
    }

    private static List<SchemaTypeEntry> BuildSchemaEntries(
        IReadOnlyCollection<DependencyProperty> dependencyProperties,
        IReadOnlyCollection<AttachedSetterEntry> attachedSetters)
    {
        var types = UiAssembly.GetTypes()
            .Where(IsSchemaRelevantType)
            .OrderBy(static type => GetElementName(type), StringComparer.Ordinal)
            .ToArray();

        var included = new HashSet<Type>(types);
        var entries = new List<SchemaTypeEntry>(types.Length);

        foreach (var type in types)
        {
            var elementName = GetElementName(type);
            var schemaTypeName = GetSchemaTypeName(type);
            var baseTypeName = GetBaseSchemaTypeName(type, included);
            var attributes = BuildAttributes(type, dependencyProperties, attachedSetters);
            var propertyElements = BuildPropertyElementsForType(type, dependencyProperties, attachedSetters);
            entries.Add(new SchemaTypeEntry(type, elementName, schemaTypeName, baseTypeName, attributes, propertyElements));
        }

        return entries;
    }

    private static IReadOnlyCollection<Type> CollectEnumTypes(
        IReadOnlyCollection<SchemaTypeEntry> typeEntries,
        IReadOnlyCollection<DependencyProperty> dependencyProperties,
        IReadOnlyCollection<AttachedSetterEntry> attachedSetters)
    {
        var enumTypes = new HashSet<Type>();

        foreach (var entry in typeEntries)
        {
            foreach (var attribute in entry.Attributes)
            {
                var enumType = Nullable.GetUnderlyingType(attribute.ValueType) ?? attribute.ValueType;
                if (enumType.IsEnum)
                {
                    enumTypes.Add(enumType);
                }
            }
        }

        foreach (var property in dependencyProperties)
        {
            var enumType = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;
            if (enumType.IsEnum)
            {
                enumTypes.Add(enumType);
            }
        }

        foreach (var attachedSetter in attachedSetters)
        {
            var enumType = Nullable.GetUnderlyingType(attachedSetter.ValueType) ?? attachedSetter.ValueType;
            if (enumType.IsEnum)
            {
                enumTypes.Add(enumType);
            }
        }

        return enumTypes.OrderBy(static type => type.Name, StringComparer.Ordinal).ToArray();
    }

    private static IReadOnlyList<SchemaAttributeEntry> BuildAttributes(
        Type type,
        IReadOnlyCollection<DependencyProperty> dependencyProperties,
        IReadOnlyCollection<AttachedSetterEntry> attachedSetters)
    {
        var attributes = new Dictionary<string, SchemaAttributeEntry>(StringComparer.Ordinal);

        foreach (var dependencyProperty in dependencyProperties)
        {
            if (dependencyProperty.IsAttached)
            {
                if (dependencyProperty.IsApplicableTo(type))
                {
                    var attachedName = dependencyProperty.OwnerType.Name + "." + dependencyProperty.Name;
                    attributes.TryAdd(attachedName, new SchemaAttributeEntry(attachedName, dependencyProperty.PropertyType));
                }

                continue;
            }

            if (dependencyProperty.OwnerType != type)
            {
                continue;
            }

            attributes.TryAdd(dependencyProperty.Name, new SchemaAttributeEntry(dependencyProperty.Name, dependencyProperty.PropertyType));
        }

        foreach (var attachedSetter in attachedSetters)
        {
            if (attachedSetter.TargetType.IsAssignableFrom(type))
            {
                attributes.TryAdd(attachedSetter.FullName, new SchemaAttributeEntry(attachedSetter.FullName, attachedSetter.ValueType));
            }
        }

        foreach (var property in type.GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly))
        {
            if (!property.CanWrite ||
                property.GetIndexParameters().Length != 0 ||
                property.GetMethod?.IsStatic == true ||
                property.SetMethod?.IsStatic == true ||
                string.Equals(property.Name, "Item", StringComparison.Ordinal))
            {
                continue;
            }

            attributes.TryAdd(property.Name, new SchemaAttributeEntry(property.Name, property.PropertyType));
        }

        foreach (var eventInfo in type.GetEvents(BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly))
        {
            attributes.TryAdd(eventInfo.Name, new SchemaAttributeEntry(eventInfo.Name, typeof(string)));
        }

        return attributes.Values.OrderBy(static attribute => attribute.Name, StringComparer.Ordinal).ToArray();
    }

    private static IReadOnlyList<PropertyElementEntry> BuildPropertyElementsForType(
        Type type,
        IReadOnlyCollection<DependencyProperty> dependencyProperties,
        IReadOnlyCollection<AttachedSetterEntry> attachedSetters)
    {
        var propertyElements = new Dictionary<string, PropertyElementEntry>(StringComparer.Ordinal);

        foreach (var property in type.GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly))
        {
            if (property.GetIndexParameters().Length != 0 ||
                property.GetMethod is null ||
                property.GetMethod.IsStatic ||
                string.Equals(property.Name, "Item", StringComparison.Ordinal))
            {
                continue;
            }

            var fullName = type.Name + "." + property.Name;
            propertyElements.TryAdd(fullName, new PropertyElementEntry(fullName));
        }

        foreach (var dependencyProperty in dependencyProperties.Where(static property => property.IsAttached))
        {
            if (dependencyProperty.IsApplicableTo(type))
            {
                var fullName = dependencyProperty.OwnerType.Name + "." + dependencyProperty.Name;
                propertyElements.TryAdd(fullName, new PropertyElementEntry(fullName));
            }
        }

        foreach (var attachedSetter in attachedSetters)
        {
            if (attachedSetter.TargetType.IsAssignableFrom(type))
            {
                propertyElements.TryAdd(attachedSetter.FullName, new PropertyElementEntry(attachedSetter.FullName));
            }
        }

        return propertyElements.Values.OrderBy(static element => element.Name, StringComparer.Ordinal).ToArray();
    }

    private static IReadOnlyList<PropertyElementEntry> BuildPropertyElements(
        IReadOnlyCollection<SchemaTypeEntry> typeEntries,
        IReadOnlyCollection<DependencyProperty> dependencyProperties,
        IReadOnlyCollection<AttachedSetterEntry> attachedSetters)
    {
        var propertyElements = new Dictionary<string, PropertyElementEntry>(StringComparer.Ordinal);

        foreach (var entry in typeEntries)
        {
            foreach (var propertyElement in entry.PropertyElements)
            {
                propertyElements.TryAdd(propertyElement.Name, propertyElement);
            }
        }

        foreach (var dependencyProperty in dependencyProperties.Where(static property => property.IsAttached))
        {
            var fullName = dependencyProperty.OwnerType.Name + "." + dependencyProperty.Name;
            propertyElements.TryAdd(fullName, new PropertyElementEntry(fullName));
        }

        foreach (var attachedSetter in attachedSetters)
        {
            propertyElements.TryAdd(attachedSetter.FullName, new PropertyElementEntry(attachedSetter.FullName));
        }

        return propertyElements.Values.OrderBy(static element => element.Name, StringComparer.Ordinal).ToArray();
    }

    private static bool IsSchemaRelevantType(Type type)
    {
        if (!type.IsVisible ||
            type.IsAbstract ||
            type.IsInterface ||
            type.IsEnum ||
            type.IsGenericTypeDefinition ||
            typeof(Delegate).IsAssignableFrom(type))
        {
            return false;
        }

        if (type.Namespace is null)
        {
            return false;
        }

        if (type.Namespace.Contains(".Diagnostics", StringComparison.Ordinal) ||
            type.Namespace.Contains(".Telemetry", StringComparison.Ordinal) ||
            type.Namespace.Contains(".Automation.InkkOops", StringComparison.Ordinal))
        {
            return false;
        }

        if (type == typeof(Color) ||
            type == typeof(Rectangle) ||
            type == typeof(Point) ||
            type == typeof(Vector2))
        {
            return false;
        }

        return type.GetConstructor(Type.EmptyTypes) is not null;
    }

    private static string GetElementName(Type type)
    {
        return AliasedElementNames.TryGetValue(type, out var alias) ? alias : type.Name;
    }

    private static string GetSchemaTypeName(Type type)
    {
        return ToCamelCase(GetElementName(type)) + "Type";
    }

    private static string GetBaseSchemaTypeName(Type type, IReadOnlySet<Type> includedTypes)
    {
        for (var current = type.BaseType; current is not null; current = current.BaseType)
        {
            if (includedTypes.Contains(current))
            {
                return GetSchemaTypeName(current);
            }
        }

        return "xamlObjectType";
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrEmpty(value) || char.IsLower(value[0]))
        {
            return value;
        }

        var chars = value.ToCharArray();
        for (var i = 0; i < chars.Length; i++)
        {
            var nextIsLower = i + 1 < chars.Length && char.IsLower(chars[i + 1]);
            chars[i] = char.ToLowerInvariant(chars[i]);
            if (nextIsLower)
            {
                break;
            }
        }

        return new string(chars);
    }

    private static void WriteSimpleAliasTypes(XmlWriter writer)
    {
        WriteSimpleRestriction(writer, "thicknessType");
        WriteSimpleRestriction(writer, "colorType");
        WriteSimpleRestriction(writer, "cornerRadiusType");
        WriteSimpleRestriction(writer, "xamlValueType");
    }

    private static void WriteSimpleRestriction(XmlWriter writer, string name)
    {
        writer.WriteStartElement("xs", "simpleType", null);
        writer.WriteAttributeString("name", name);
        writer.WriteStartElement("xs", "restriction", null);
        writer.WriteAttributeString("base", "xs:string");
        writer.WriteEndElement();
        writer.WriteEndElement();
    }

    private static void WriteEnumTypes(XmlWriter writer, IEnumerable<Type> enumTypes)
    {
        foreach (var enumType in enumTypes)
        {
            writer.WriteStartElement("xs", "simpleType", null);
            writer.WriteAttributeString("name", GetEnumTypeName(enumType));
            writer.WriteStartElement("xs", "restriction", null);
            writer.WriteAttributeString("base", "xs:string");

            foreach (var value in Enum.GetNames(enumType))
            {
                writer.WriteStartElement("xs", "enumeration", null);
                writer.WriteAttributeString("value", value);
                writer.WriteEndElement();
            }

            writer.WriteEndElement();
            writer.WriteEndElement();
        }
    }

    private static string GetEnumTypeName(Type enumType)
    {
        return ToCamelCase(enumType.Name) + "EnumType";
    }

    private static void WriteObjectLikeType(XmlWriter writer, string typeName)
    {
        writer.WriteStartElement("xs", "complexType", null);
        writer.WriteAttributeString("name", typeName);

        writer.WriteStartElement("xs", "sequence", null);
        writer.WriteAttributeString("minOccurs", "0");
        writer.WriteAttributeString("maxOccurs", "unbounded");
        writer.WriteStartElement("xs", "any", null);
        writer.WriteAttributeString("processContents", "lax");
        writer.WriteAttributeString("minOccurs", "0");
        writer.WriteAttributeString("maxOccurs", "unbounded");
        writer.WriteEndElement();
        writer.WriteEndElement();

        writer.WriteStartElement("xs", "anyAttribute", null);
        writer.WriteAttributeString("processContents", "lax");
        writer.WriteEndElement();

        writer.WriteEndElement();
    }

    private static void WriteSchemaTypes(XmlWriter writer, IReadOnlyCollection<SchemaTypeEntry> typeEntries)
    {
        foreach (var entry in typeEntries)
        {
            writer.WriteStartElement("xs", "complexType", null);
            writer.WriteAttributeString("name", entry.SchemaTypeName);
            writer.WriteStartElement("xs", "complexContent", null);
            writer.WriteStartElement("xs", "extension", null);
            writer.WriteAttributeString("base", entry.BaseTypeName);

            foreach (var attribute in entry.Attributes)
            {
                writer.WriteStartElement("xs", "attribute", null);
                writer.WriteAttributeString("name", attribute.Name);
                writer.WriteAttributeString("type", MapXmlType(attribute.ValueType));
                writer.WriteEndElement();
            }

            writer.WriteEndElement();
            writer.WriteEndElement();
            writer.WriteEndElement();
        }
    }

    private static string MapXmlType(Type rawType)
    {
        var type = Nullable.GetUnderlyingType(rawType) ?? rawType;

        if (type.IsEnum)
        {
            return GetEnumTypeName(type);
        }

        if (type == typeof(string) || type == typeof(char))
        {
            return "xs:string";
        }

        if (type == typeof(bool))
        {
            return "xs:boolean";
        }

        if (type == typeof(int))
        {
            return "xs:int";
        }

        if (type == typeof(float))
        {
            return "xs:float";
        }

        if (type == typeof(double))
        {
            return "xs:double";
        }

        if (type == typeof(decimal))
        {
            return "xs:decimal";
        }

        if (type == typeof(Thickness))
        {
            return "thicknessType";
        }

        if (type == typeof(CornerRadius))
        {
            return "cornerRadiusType";
        }

        if (type == typeof(Color))
        {
            return "colorType";
        }

        return "xamlValueType";
    }

    private static void WritePropertyElementDeclarations(XmlWriter writer, IReadOnlyCollection<PropertyElementEntry> propertyElements)
    {
        foreach (var propertyElement in propertyElements)
        {
            writer.WriteStartElement("xs", "element", null);
            writer.WriteAttributeString("name", propertyElement.Name);
            writer.WriteAttributeString("type", "xamlPropertyElementType");
            writer.WriteEndElement();
        }
    }

    private static void WriteElementDeclarations(XmlWriter writer, IReadOnlyCollection<SchemaTypeEntry> typeEntries)
    {
        foreach (var entry in typeEntries)
        {
            writer.WriteStartElement("xs", "element", null);
            writer.WriteAttributeString("name", entry.ElementName);
            writer.WriteAttributeString("type", entry.SchemaTypeName);
            writer.WriteEndElement();
        }
    }

    private sealed record SchemaTypeEntry(
        Type Type,
        string ElementName,
        string SchemaTypeName,
        string BaseTypeName,
        IReadOnlyList<SchemaAttributeEntry> Attributes,
        IReadOnlyList<PropertyElementEntry> PropertyElements);

    private sealed record SchemaAttributeEntry(string Name, Type ValueType);

    private sealed record PropertyElementEntry(string Name);

    private sealed record AttachedSetterEntry(Type OwnerType, string PropertyName, Type TargetType, Type ValueType)
    {
        public string FullName => OwnerType.Name + "." + PropertyName;
    }
}