using System;
using System.Collections.Generic;

namespace InkkSlinger;

internal sealed class DataGridState
{
    public List<DataGridColumnState> Columns { get; } = new();

    public List<DataGridRowState> Rows { get; } = new();

    public DataGridSelectionState Selection { get; } = new();

    public DataGridEditState Edit { get; } = new();

    public Type? AutoGeneratedItemType { get; set; }
}

internal sealed class DataGridColumnState
{
    public required DataGridColumn Column { get; init; }

    public int DisplayIndex { get; set; }

    public float Width { get; set; }

    public DataGridSortDirection SortDirection { get; set; }

    public string HeaderText =>
        string.IsNullOrWhiteSpace(Column.Header)
            ? (string.IsNullOrWhiteSpace(Column.BindingPath) ? "Value" : Column.BindingPath)
            : Column.Header;
}

internal sealed class DataGridRowState
{
    public int RowIndex { get; set; }

    public object? Item { get; set; }

    public bool AreDetailsVisible { get; set; }
}

internal sealed class DataGridSelectionState
{
    public int SelectedRowIndex { get; set; } = -1;

    public int SelectedColumnIndex { get; set; } = -1;

    public int CurrentRowIndex { get; set; } = -1;

    public int CurrentColumnIndex { get; set; } = -1;
}

internal sealed class DataGridEditState
{
    public int EditingRowIndex { get; set; } = -1;

    public int EditingColumnIndex { get; set; } = -1;

    public UIElement? ActiveEditorElement { get; set; }

    public DataGridEditTriggerSource TriggerSource { get; set; }

    public object? OriginalValue { get; set; }

    public bool IsEditing => EditingRowIndex >= 0 && EditingColumnIndex >= 0 && ActiveEditorElement != null;

    public void Reset()
    {
        EditingRowIndex = -1;
        EditingColumnIndex = -1;
        ActiveEditorElement = null;
        TriggerSource = DataGridEditTriggerSource.None;
        OriginalValue = null;
    }
}
